[functions."swap"]
schedule = "*/3 * * * *"
[functions."back-swap"]
schedule = "*/4 * * * *"
[functions."sell"]
schedule = "*/10 * * * *"
[functions."large-buy"]
schedule = "*/15 * * * *"
[functions]
  node_bundler = "esbuild"